story/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('story9/', include('story9.urls')),
    path('story8/', include('story8.urls')),
    path('story7/', include('story7.urls')),
    path('story6/', include('story6.urls')),
    path('', include('story5.urls')),
    # path('', include(('story4.urls'), namespace='story4')),
    # path('story1/', include(('profile_page.urls'), namespace='story1'))
]

story9/urls.py
from django.urls import path
from . import views

app_name = 'story9'

urlpatterns = [
    path('', views.index, name='index'),
    path('register/', views.register, name='register'),
    path('login/', views.logon, name='login'),
    path('logoff/', views.logoff, name='logoff')
]

story9/models.py
from django.db import models

# Create your models here.

story9/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm

form_class_str = "form-control"
class RegistrationForm(UserCreationForm):
    username = forms.CharField(label="Username", widget=forms.TextInput(attrs={
        "class" : form_class_str,
        "placeholder" : "Username (min. 9 characters)" # I wanted to write this as 君の名は so badly
    }))

    password1 = forms.CharField(label="Password", widget=forms.TextInput(attrs={
        "class" : form_class_str,
        "placeholder" : "Password (min. 8 characters)",
        "type" : "password"
    }))

    password2 = forms.CharField(label="Confirm Password", widget=forms.TextInput(attrs={
        "class" : form_class_str,
        "placeholder" : "Confirm your password",
        "type" : "password"
    }))

    class Meta:
        model = User
        fields = ["username", "password1", "password2"]

class LoginForm(AuthenticationForm):
    username = forms.CharField(label="Username", widget=forms.TextInput(attrs={
        "class" : form_class_str,
        "placeholder" : "Username"
    }))

    password = forms.CharField(label="Password", widget=forms.TextInput(attrs={
        "class" : form_class_str,
        "placeholder" : "Password",
        "type" : "password"
    }))

    class Meta:
        fields = "__all__"

story9/views.py
# ideas/boilerplate/basically this entire story taken/inspired from Matthew T.P.'s work
# on https://gitlab.com/matthewsolomon_/story6/-/blob/master/story9. Thanks, Matt!
from django.shortcuts import render, redirect
from django.contrib.auth import login , logout, authenticate
from django.contrib.auth.models import User
from .forms import RegistrationForm, LoginForm
from random import randint
# Create your views here.
    
list_of_hellos = [
    'halo, {}!',
    'hello, {}!',
    'hallo, {}!',
    'おっす、 {}!',
    'привет, {}!',
    '你好, {}!',
    '哈囉, {}!',
    'xin chào, {}!',
    'salut, {}!',
    '안녕, {}!',
    'goddag, {}!',
    'olá, {}!',
    'moikka, {}!',
    'салам, {}!'
]

def index(request):
    context = {
        'title': 'Do People Even Remember MySpace?',
        'greeting': list_of_hellos[randint(0, (len(list_of_hellos)-1))].format(request.user.username)
    }
    return render(request, 'story9/index.html', context)

def register(request):
    if request.user.is_authenticated:
        return redirect("story9:index")
    context = {
        "register_form": RegistrationForm,
        "title": 'Registration'
    }

    if request.method == "POST":
        register_candidate = RegistrationForm(request.POST)
        if register_candidate.is_valid():
            register_candidate.save()
            new_user = authenticate(
                username = register_candidate.cleaned_data['username'],
                password = register_candidate.cleaned_data['password1']
            )
            login(request, new_user)

            return redirect("story9:index")
        elif register_candidate.errors:
            context["error"] = "Please fill all forms correctly."
    return render(request, 'story9/register.html', context)



def logon(request):
    context = {
        "login_form": LoginForm, 
        "title": "Login"
    }
    if request.user.is_authenticated:
        return redirect("story9:index")

    if request.method == "POST":
        login_attempt = LoginForm(data = request.POST)
        if login_attempt.is_valid():
            user_account = login_attempt.get_user()
            login(request, user_account)
            return redirect("story9:index")
        elif login_attempt.errors:
            context["error"] = "Login data not valid."
    return render(request, 'story9/login.html', context)



def logoff(request):
    if request.user.is_authenticated:
        logout(request)
    return redirect("story9:index")
    

story9/templates/story9/base.html
<!DOCTYPE html>

{% load static %}

<html>

<head>
<title>{{ title }}</title>
{% block additional-style %}
{% endblock %}
<meta name="viewport" content="width=device-width, initial-scale=1.0"> 
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
<link href="{% static 'story7/styles.css' %}" rel="stylesheet" type="text/css">
<link href="{% static 'story9/styles.css' %}" rel="stylesheet" type="text/css">
</head>

<body>
    <nav class="navbar">
        <div class="container">
            <a class="navbar-brand navlink" href="{% url 'story9:index' %}">{{ title }}</a>
        </div>
    </nav>
    <div id="content" class="container col my-3 d-flex align-items-center justify-content-center flex-wrap">
    {% block content %}
    {% endblock %}
    </div>
</body>
</html>

story9/templates/story9/index.html
{% extends 'story9/base.html' %}
{% load static %}
{% block content %}
<div class="card container p-3 align-content-center">
    {% if not request.user.is_authenticated %}
    <h3>who are you?</h3>
    <a href="{% url 'story9:login' %}" class="custom-button my-3 text-center">Login</a>
    <a href="{% url 'story9:register' %}" class="custom-button my-3 text-center">Register</a> 

    {% else %}
    <h3>{{ greeting }}</h3>
    <h4>now go away</h2>
    <a href="{% url 'story9:logoff' %}" class="custom-button my-3 text-center">Log Off</a>
    {% endif %}
</div>
{% endblock %}

story9/templates/story9/login.html
{% extends 'story9/base.html' %}
{% load static %}
{% block content %}
<div class="card container p-3">
    <form method="POST" action="{% url 'story9:login' %}" class="login-form rounded-lg d-flex flex-column">
        {% if error %}
            <p class="text-center p-2 bg-danger rounded-lg">{{ error }}</p>
        {% endif %}
        <h3 class="mb-3 text-center">Login</h3>
        {% csrf_token %}
        {% for field in login_form %}
            <div class="form-group">
                <label>{{ field.label }}</label>
                {{ field }}
            </div>
        {% endfor %}
        <button type="submit" class="custom-button btn">Login</button>
        <p class="my-3">Don't have an account?<p>
        <a class="custom-button my-3" href="{% url 'story9:register' %}">Make one</a>
    </form>
</div>
{% endblock %}

story9/templates/story9/register.html
{% extends 'story9/base.html' %}
{% load static %}
{% block content %}
<div class="card container p-3">
    {% if error %}
            <p class="text-center p-2 bg-danger rounded-lg">
                {{ error }}
            </p>
    {% endif %}
    <form method="POST" action="{% url 'story9:register' %}" class="card login-form rounded-lg d-flex flex-column justify-content-center">
        <h3 class="text-center mb-3">Create an account</h3>
        {% csrf_token %}
        {% for field in register_form %}
            <div class="form-group">
                <label>{{ field.label }}</label>
                {{ field }}
            </div>
        {% endfor %}
        <button type="submit" class="custom-button btn my-3">Register Account</button>
    </form>

</div>
{% endblock %}