story/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('story9/', include('story9.urls')),
    path('story8/', include('story8.urls')),
    path('story7/', include('story7.urls')),
    path('story6/', include('story6.urls')),
    path('', include('story5.urls')),
    # path('', include(('story4.urls'), namespace='story4')),
    # path('story1/', include(('profile_page.urls'), namespace='story1'))
]

story6/urls.py
from django.urls import path
from . import views

app_name = 'story6'

urlpatterns = [
    path('', views.index, name='index'),
    path('add_kegiatan/', views.add_kegiatan, name='add_kegiatan'),
    path('add_peserta/', views.add_peserta, name='add_peserta'),
    path('delete_peserta/<int:peserta_id>', views.delete_peserta, name='delete_peserta'),
    path('delete_kegiatan/<int:kegiatan_id>', views.delete_kegiatan, name='delete_kegiatan'),
]

story6/models.py
from django.db import models

# Create your models here.
class Kegiatan(models.Model):
    name = models.CharField(max_length = 256, unique=True)
    def __str__(self):
        return self.name
    def participants(self):
        return Peserta.objects.filter(kegiatan = self)
    class Meta:
        ordering = ['-name']

class Peserta(models.Model):
    name = models.CharField(max_length = 256, unique=True)
    kegiatan = models.ForeignKey(Kegiatan, on_delete = models.CASCADE)
    def __str__(self):
        return self.name
    class Meta:
        ordering = ['-name']

story6/forms.py
from django import forms
from .models import Kegiatan, Peserta
from django.core.exceptions import ValidationError

class KegiatanForm(forms.ModelForm):
    class Meta:
        model = Kegiatan
        fields = "__all__"

class PesertaForm(forms.Form):
    name = forms.CharField(label='Nama anda', max_length=256)
    kegiatan = forms.ModelChoiceField(queryset=Kegiatan.objects.all())
    
    def clean_name(self):
        name = self.cleaned_data['name']
        if Peserta.objects.filter(name=name).exists():
            raise ValidationError("Peserta already exists")
        return name

story6/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from .models import Kegiatan, Peserta
from .forms import KegiatanForm, PesertaForm
from django.urls import reverse

# Create your views here.
def index(request):
    context = {
        'kegiatan_list': Kegiatan.objects.all()
    }
    return render(request, 'story6/index.html', context)
    
def add_kegiatan(request):
    if request.method == 'POST':
        add_kegiatan_form = KegiatanForm(request.POST)
        if add_kegiatan_form.is_valid():
            add_kegiatan_form.save()
            messages.add_message(request, messages.SUCCESS,
            "Kegiatan {} berhasil ditambahkan!".format(request.POST.get('name')))
            return redirect(reverse('story6:index'))
        else:
            messages.add_message(request, messages.ERROR,
            "Kegiatan {} TIDAK berhasil ditambahkan!".format(request.POST.get('name')))

    return render(request, 'story6/add_kegiatan.html')

def add_peserta(request):
    if request.method == 'POST':
        kegiatan = Kegiatan.objects.get(id = request.POST.get('kegiatan'))
        # print(kegiatan)
        nama_peserta = request.POST.get('name')
        add_peserta_form = PesertaForm(request.POST)
        if add_peserta_form.is_valid():
            existing_peserta, new_peserta = Peserta.objects.get_or_create(name = nama_peserta,
            defaults={'name': nama_peserta, 'kegiatan': kegiatan})
            if (existing_peserta not in Peserta.objects.all()) or new_peserta:
                existing_peserta.save()
                messages.add_message(request, messages.SUCCESS,
                "Peserta {} berhasil didaftarkan!".format(nama_peserta))
                # print("Peserta {} berhasil didaftarkan!".format(nama_peserta))
                return redirect(reverse('story6:index'))
        else:
            # print(add_peserta_form.errors)
            # print(add_peserta_form.kegiatan)
            messages.add_message(request, messages.ERROR,
            "Peserta {} TIDAK berhasil didaftarkan!".format(request.POST.get('name')))
            # print("Peserta {} TIDAK berhasil didaftarkan!".format(request.POST.get('name')))
    return redirect(reverse('story6:index'))

def delete_peserta(request, peserta_id):
    if request.method == 'POST':
        # print("Request is correct")
        peserta = Peserta.objects.get(id = peserta_id)
        # print("Peserta")
        peserta.delete()
        messages.add_message(request, messages.SUCCESS,
        "Peserta {} berhasil ditidakjadidaftarkan!".format(peserta))
    return redirect(reverse('story6:index'))
    
def delete_kegiatan(request, kegiatan_id):
    if request.method == 'POST':
        kegiatan = Kegiatan.objects.get(id = kegiatan_id)
        kegiatan.delete()
        messages.add_message(request, messages.SUCCESS,
        "Kegiatan {} sekarang sudah jadi wacana saja :(".format(kegiatan))
    return redirect(reverse('story6:index'))
    

story6/templates/story6/add_kegiatan.html
{% extends 'story6/base.html' %}
{% load static %}
{% block content %}
<div class = "card">
<form action = "{% url 'story6:add_kegiatan' %}" method = 'POST'>
    {% csrf_token %}
    <input name = "name" required>
    <button class="submit-btn" type="submit">Buat Kegiatan</button>
</form>
</div>
{% endblock %}

story6/templates/story6/base.html
<!DOCTYPE html>

{% load static %}

<html>

<head>
<title>Wacana Disorganizer</title>
{% block additional-style %}
{% endblock %}
<meta name="viewport" content="width=device-width, initial-scale=1.0"> 
<link href="{% static 'story6/styles.css' %}" rel="stylesheet" type="text/css">
</head>

<body>
    {% block display-messages %}
        {% if messages %}
        <script>
        {% for message in messages %}
            alert("{{ message }}");
        {% endfor %}
        </script>
    {% endif %}
    {% endblock %}
    <header>
        <nav id="nav-container">
            <div class="nav-left">
                <a class="navlink horizontal" href="{% url 'story6:index' %}">Wacana Disorganizer</a>
            </div>
            <div class="nav-right">
                <a class="navlink" href="{% url 'story6:add_kegiatan' %}">Add Kegiatan</a>
            </div>
        </nav>
    </header>
    <div id="content">
    {% block content %}
    {% endblock %}
    </div>
</body>
</html>

story6/templates/story6/index.html
{% extends 'story6/base.html' %}
{% load static %}
{% block content %}
{% for kegiatan in kegiatan_list %}
<div class = "card">
    <div class = "card-row">
        <p>{{ kegiatan.name }}</p>
        <form action="{% url 'story6:delete_kegiatan' kegiatan.id %}" method="POST">
                {% csrf_token %}
                <button class = "del-btn" title = "Cancel kegiatan" alt = "Cancel kegiatan">Cancel</button>
        </form>
    </div>
    {% for peserta in kegiatan.participants %}
        <div class = "card-row">
            <p>{{ peserta.name }}</p>
            <form action="{% url 'story6:delete_peserta' peserta.id %}" method="POST">
                {% csrf_token %}
                <button class = "del-btn" title = "Hapus peserta" alt = "Hapus peserta">&times;</button>
            </form>
        </div>
    {% endfor %}
    <form action = "{% url 'story6:add_peserta' %}" method = 'POST' class="card-row">
        {% csrf_token %}
        <input name = "name" required placeholder = "Jatah satu orang satu kegiatan">
        <input name = "kegiatan" value = "{{ kegiatan.id }}" type = "hidden">
        <button class="submit-btn" type="submit">Daftarkan</button>
    </form>
</div>
{% endfor %}
{% endblock %}