story/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('story9/', include('story9.urls')),
    path('story8/', include('story8.urls')),
    path('story7/', include('story7.urls')),
    path('story6/', include('story6.urls')),
    path('', include('story5.urls')),
    # path('', include(('story4.urls'), namespace='story4')),
    # path('story1/', include(('profile_page.urls'), namespace='story1'))
]

story5/urls.py
from django.urls import path
from . import views

app_name = 'story5'

urlpatterns = [
    path('', views.index, name='index'),
    path('add_matkul/', views.add_matkul, name='add_matkul'),
    path('detail_matkul/<slug:matkul_id>', views.detail_matkul, name='detail_matkul'),
    path('delete_matkul/<slug:matkul_id>', views.delete_matkul, name='delete_matkul')
]

story5/models.py
from django.core.exceptions import ValidationError
from django.core.validators import RegexValidator
from django.utils.translation import gettext_lazy as _
from django.db import models

# Create your models here.

# Mata kuliah tersebut meliputi nama mata kuliah, dosen pengajar, 
# jumlah sks, deskripsi mata kuliah, semester tahun(contoh: Gasal 2019/2020) 
# dan ruang kelas dimana mata kuliah tersebut dilaksanakan.
class MataKuliah(models.Model):

    def validate_semester(candidate_string):
        try:
            candidate = candidate_string.split(' ')
            if len(candidate) == 2:
                if candidate[0].upper() == 'GASAL' or candidate[0].upper() == 'GENAP':
                    years = candidate[1].split('/')
                    if (int(years[1]) - int(years[0])) == 1:
                        return None
            raise ValidationError(
                _('%(candidate_string) is not a valid term year'),
                params={'candidate_string': candidate_string},
            )
        except:
            raise ValidationError(
                _('%(candidate_string) is not a valid term year'),
                params={'candidate_string': candidate_string},
            )
    nama_matkul = models.TextField(max_length=100);
    nama_dosen = models.TextField(max_length=100);
    jumlah_sks = models.IntegerField();
    deskripsi = models.TextField(max_length=2048);
    # this one will be validated using a custom one
    # because regex can't match for increments. This is 
    # just for illustration
    # semester_tahun = r'^((Gasal|Genap) {year}/{year+1})$'
    semester_tahun = models.CharField(max_length=15, validators=[validate_semester]);
    # ruangan = r'^((A[1-9]\.[0-9]{2})|((?P<bldg>[1-3])\.(?P=bldg)[0-9]{3})|(online))$'
    ruangan = models.CharField(max_length=16, validators=[
        RegexValidator(regex = 
            r'^((A[1-9]\.[0-9]{2})|((?P<bldg>[1-3])\.(?P=bldg)[0-9]{3})|(online))$'
        )]);
    # kode_matkul = r'^([A-Z]{4}[0-9]{6})$'
    kode_matkul = models.CharField(max_length=10, unique=True, validators=[
        RegexValidator(regex=
            r'^([A-Z]{4}[0-9]{6})$'
        )]);

    def __str__(self):
        return self.nama_matkul

story5/forms.py
from django import forms
from .models import MataKuliah

class MataKuliahForm(forms.ModelForm):
    class Meta:
        model = MataKuliah
        fields = "__all__"
        
    # def clean():
        # cleaned_data = super().clean()

story5/views.py
from django.shortcuts import render, redirect
from .models import MataKuliah
from .forms import MataKuliahForm
from django.contrib import messages

def index(request):
    context = {'matkul_list': MataKuliah.objects.all().order_by('-kode_matkul')}
    return render(request, "story5/index.html", context)

def add_matkul(request):
    if request.method == "POST":
        add_request_form = MataKuliahForm(request.POST)
        if add_request_form.is_valid():
            add_request_form.save()
            messages.add_message(request, messages.SUCCESS, 
            "Mata kuliah {} berhasil ditambahkan!".format(request.POST["nama_matkul"]))
        else:
            messages.add_message(request, messages.ERROR, 
            "Mata kuliah {} TIDAK berhasil ditambahkan.".format(request.POST["nama_matkul"]))
            
    return render(request, "story5/add_matkul.html")

def detail_matkul(request, matkul_id):
    context = {'matkul': MataKuliah.objects.get(kode_matkul=matkul_id)}
    return render(request, "story5/detail_matkul.html", context)

def delete_matkul(request, matkul_id):
    if request.method == "POST":
        matkul = MataKuliah.objects.get(kode_matkul=matkul_id)
        matkul.delete()
        messages.add_message(request, messages.SUCCESS,
        "Mata kuliah {} sudah terhapus!".format(matkul.nama_matkul))
    return redirect("story5:index")

story5/templates/story5/add_matkul.html
{% extends 'story5/base.html' %}
{% load static %}
<!-- ADD! -->
{% block content %}
    <div class = "card">
        <form action="{% url 'story5:add_matkul' %}" method="POST">
        {% csrf_token %}
            <div class = "row">
                <div class="column">
                    <!-- <h3 class = "heading">{{ matkul.nama_matkul }}</h3> -->
                    <input id = "nama-matkul-input" placeholder = "Nama Mata Kuliah" name = "nama_matkul" required>
                    
                </div>
                <div class="column">
                    <!-- <h2 class = "subheading">{{ matkul.kode_matkul }}</h2> -->
                    <input id = "kode-matkul-input" placeholder = "Kode Mata Kuliah" name = "kode_matkul" required>
                    <p class = "input-subtitle">Format: Empat (4) huruf kapital diikuti enam (6) angka</p>
                    
                </div>
            </div>
            
            <div class = "row">
                <div class="column">
                    <!-- <p>{{ matkul.nama_dosen }}</p> -->
                    <input id = "nama-dosen-input" placeholder = "Nama Dosen Pengampu" name = "nama_dosen" required>
                    <!-- <p>{{ matkul.ruangan }}</p> -->
                    <input id = "ruangan-input" placeholder = "Ruangan" name = "ruangan" required>
                    <p class = "input-subtitle">Format: Ruangan sesuai format di Fasilkom (misal: A1.22 atau 2.2303).<br> Untuk kelas online, tulis "online".</p>
                    
                    
                </div>
                <div class="column">
                    <!-- <p>{{ matkul.jumlah_sks }}</p> -->
                    <input id = "jumlah-input" type = "number" value = 1 name = "jumlah_sks" required>
                    <!-- <p>{{ matkul.jumlah_sks }}</p> -->
                    <input id = "semester-tahun-input" placeholder = "Semester Tahun" name = "semester_tahun" required>
                    <p class = "input-subtitle">Format: Satu (1) kata, "Gasal" atau "Genap", diikuti tahun berbentuk seperti 2019/2020</p>
                    
                    
                </div>
            </div>
            <div class = "card-paragraph row">
                <div class= "column">
                    <!-- <p>{{ matkul.deskripsi }}</p> -->
                    <textarea name = "deskripsi" placeholder = "Deskripsikan mata kuliah ini" required></textarea>
                </div>
            </div>
        <div class ="row">
            <div class = "column">
                <button class="submit-btn" type="submit">Add Mata Kuliah</button>
            </div>
        </div>
        </form>
    </div>
{% endblock %}

story5/templates/story5/base.html
<!DOCTYPE html>

{% load static %}

<html>

<head>
<title>Bukan SCeLE</title>
{% block additional-style %}
{% endblock %}
<meta name="viewport" content="width=device-width, initial-scale=1.0"> 
<link href="{% static 'story5/styles.css' %}" rel="stylesheet" type="text/css">
</head>

<body>
    {% block display-messages %}
        {% if messages %}
        <script>
        {% for message in messages %}
            alert("{{ message }}");
        {% endfor %}
        </script>
    {% endif %}
    {% endblock %}
    <header>
        <nav id="nav-container">
            <div class="nav-left">
                <a class="navlink horizontal" href="{% url 'story5:index' %}">Bukan SCeLE</a>
            </div>
            <div class="nav-right">
                <a class="navlink" href="{% url 'story5:add_matkul' %}">Add Matkul</a>
            </div>
        </nav>
    </header>
    <div id="content">
    {% block content %}
    {% endblock %}
    </div>
</body>
</html>

story5/templates/story5/detail_matkul.html
{% extends 'story5/base.html' %}
{% load static %}
<!-- DETAIL! -->
{% block content %}
    <div class = "card">
        <div class = "column">
            <h3 class = "heading">{{ matkul.nama_matkul }}</h3>
            <h4 class = "subheading">{{ matkul.kode_matkul }}</h2>
        </div>
        <div class = "row">
            <div class = "column">
                <p>Dosen: {{ matkul.nama_dosen }}</p>
                <p>Ruangan: {{ matkul.ruangan }}</p>
            </div>
            <div class = "column">
                <p>Semester: {{ matkul.semester_tahun }}</p>
                <p>Jumlah SKS: {{ matkul.jumlah_sks }}</p>
            </div>
        </div>
        <div class = "card-paragraph row">
            <div class = "column">
            <p>Deskripsi:</p>
            <br>
            <p>{{ matkul.deskripsi }}</p>
            </div>
        </div>
    </div>
{% endblock %}

story5/templates/story5/index.html
{% extends 'story5/base.html' %}
{% load static %}
<!-- INDEX! -->
{% block content %}
    {% for matkul in matkul_list %}
        <div class = "card">
            <div class = "card-top">
                <p>{{ matkul.kode_matkul }}</p>
                <form action="{% url 'story5:delete_matkul' matkul.kode_matkul %}" method="POST">
                    {% csrf_token %}
                <button class = "del-btn" title = "Delete mata kuliah" alt = "Delete mata kuliah">&times;</button>
                </form>
            </div>
            <a href = "{% url 'story5:detail_matkul' matkul.kode_matkul %}" class = "heading"><h3>{{ matkul.nama_matkul }}</h3></a>
            <p>Dosen: {{ matkul.nama_dosen }}</p>
            <p>Ruangan: {{ matkul.ruangan }}</p>
    </div>
    {% empty %}
        <div class = "huge-card">
            <p>There's nothing here, yet</p>
        </div>
    {% endfor %}
{% endblock %}