story/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('story9/', include('story9.urls')),
    path('story8/', include('story8.urls')),
    path('story7/', include('story7.urls')),
    path('story6/', include('story6.urls')),
    path('', include('story5.urls')),
    # path('', include(('story4.urls'), namespace='story4')),
    # path('story1/', include(('profile_page.urls'), namespace='story1'))
]

story8/urls.py
from django.urls import path
from . import views

app_name = 'story8'

urlpatterns = [
    path('', views.index, name='index'),
    path('get_books/', views.get_books, name='get_books'),
]

story8/models.py
from django.db import models

# Create your models here.

story8/views.py
from django.shortcuts import render
from django.http import JsonResponse
import urllib3
import json

# Create your views here.
def index(request):
    context = {
        'title': 'Library Exodus'
    }
    return render(request, 'story8/index.html', context)
    
def get_books(request):
    # thanks Mustafa! :D
    http = urllib3.PoolManager()
    request_arguments = "q="
    request_arguments += request.GET.get('q', '')
    request_arguments += (('&maxResults=' + request.GET['maxResults']) 
                         if (request.GET.get('maxResults', '') != '') else '')
    request_arguments += (('&startIndex=' + request.GET['startIndex']) 
                         if (request.GET.get('startIndex', '') != '') else '')
    response = http.request(
        "GET", "https://www.googleapis.com/books/v1/volumes?" + request_arguments)
    return JsonResponse(json.loads(response.data.decode('utf8')))

story8/templates/story8/base.html
<!DOCTYPE html>

{% load static %}

<html>

<head>
<title>{{ title }}</title>
{% block additional-style %}
{% endblock %}
<meta name="viewport" content="width=device-width, initial-scale=1.0"> 
<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
<script src="https://code.jquery.com/jquery-1.12.4.js"></script>
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
<script src="{% static 'story8/script.js' %}"></script>
<link href="{% static 'story7/styles.css' %}" rel="stylesheet" type="text/css">
<link href="{% static 'story8/styles.css' %}" rel="stylesheet" type="text/css">
</head>

<body>
    <nav class="navbar">
        <div class="container">
            <a class="navbar-brand navlink" href="{% url 'story8:index' %}">{{ title }}</a>
        </div>
    </nav>
    <div id="content" class="container col my-3 d-flex align-items-center justify-content-center flex-wrap">
    {% block content %}
    {% endblock %}
    </div>
</body>
</html>

story8/templates/story8/index.html
{% extends 'story8/base.html' %}
{% load static %}
{% block content %}
<form id = "search-form">
    <input type="search" class="form-control" id="search-query" placeholder="Book Name">
    <small class="form-text text-muted">Search for a book!</small>
    <input type="submit" class="btn btn-primary" value="🔍 Search">

</form>

<div id="results" class="container">
</div>
{% endblock %}